.TH git\-parallel
.SH NAME
.PP
git\-parallel \- Run the command in parallel much to multiple repositories
.SH Synopsis
.RS
.IP \(bu 2
git\-parallel [\-h] [\-n] [\-j <jobs>] [\-e <command>]
.RE
.SH Usage
.PP
.RS
.nf
git-parallel commands are:  
    -h  show help  
    -c  put a color on the result  
    -j  max job count  
    -e  command to be executed  
.fi
.RE
.PP
ex)
.PP
.RS
.nf
$ git parallel -c -j 4 -e "pull --rebase"
.fi
.RE
.SH What's this?
.PP
This command is executed in parallel to the git repository in the current directory directly under.
.PP
.RS
.nf
$ tree -L 1
.
├── git_repo1
├── git_repo2
├── git_repo3
├── git_repo4
├── not_git_repo -> command not execute!
├── git_repo5
├── git_repo6
└── git_repo7
.fi
.RE
.PP
However repository to the presence of the file named .git\-freeze is ignored.
.PP
.RS
.nf
$ $(cd git_repo1 && touch .git-freeze)
$ tree -L 1
.
├── git_repo1 -> command not execute!
├── git_repo2
├── git_repo3
└── git_repo4
.fi
.RE
.PP
Author
.PP
Copyright (c) 2013 - 2021 Hiroshi IKEGAMI
.PP
MIT License
.PP
Permission is hereby granted, free of charge, to any person obtaining
.br
a copy of this software and associated documentation files (the
.br
"Software"), to deal in the Software without restriction, including
.br
without limitation the rights to use, copy, modify, merge, publish,
.br
distribute, sublicense, and/or sell copies of the Software, and to
.br
permit persons to whom the Software is furnished to do so, subject to
.br
the following conditions:
.br
.PP
The above copyright notice and this permission notice shall be
.br
included in all copies or substantial portions of the Software.
.br
.PP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
.br
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.br
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
.br
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
.br
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
.br
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
.br
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.br
