#! /usr/bin/env bash

#
# git parallel -- Run the command in parallel much to multiple repositories
#
# USAGE:
#
#   git-parallel [OPTIONS] -- [GITCMD|:::CMD] # Run the command in parallel much to multiple repositories.
#
# OPTIONS:
#
#   * [-h|--help]                           # Show this help.
#   * [-j|--jobs] job-count                 # Execute in parallel with \`job-count\`
#   * [-m|--maxdepth] depth-count           # Search target git-repositories in maxdepth.
#   * [-V|--version]                        # Show git-parallel version info.
#   * [-c|--color] auto|always|never        # Configure output color.
#   * [-l|--list]                           # List up target git repositories.
#   * [-q|--silent]                         # Execute silent. (no output)
#   * [-v|--verbose]                        # Execute verbose. (default.)
#   * [-d|--targets] target-derectory       # Specified target git-repositories
#   * [-F|--freeze] repository-path         # Generate .git-parallel.freeze file.
#
# Author
#
# Copyright (c) 2013 - 2021 Hiroshi IKEGAMI
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

export GIT_PARALLEL_DEAULT_COLOR_MODE="${GIT_PARALLEL_DEAULT_COLOR_MODE:-"auto"}"
export GIT_PARALLEL_DEAULT_SILENT_MODE="${GIT_PARALLEL_DEAULT_SILENT_MODE:-"FALSE"}"
export GIT_PARALLEL_DEAULT_JOBS="${GIT_PARALLEL_DEAULT_JOBS:-"2"}"
export GIT_PARALLEL_DEAULT_MAXDEPTH="${GIT_PARALLEL_DEAULT_MAXDEPTH:-""}"
export GIT_PARALLEL_DEAULT_START_DIR="${GIT_PARALLEL_DEAULT_START_DIR:-$(cd ./ && pwd)}"

trap git::parallel::exit HUP INT QUIT TERM

git::parallel::help() {
cat << HELP >&2
USAGE:

  git-parallel [OPTIONS] -- [GITCMD|:::CMD] # Run the command in parallel much to multiple repositories.

OPTIONS:

  * [-h|--help]                             # Show this help.
  * [-j|--jobs] job-count                   # Execute in parallel with \`job-count\`
  * [-m|--maxdepth] depth-count             # Search target git-repositories in maxdepth.
  * [-V|--version]                          # Show git-parallel version info.
  * [-c|--color] auto|always|never          # Configure output color.
  * [-l|--list]                             # List up target git repositories.
  * [-q|--silent]                           # Execute silent. (no output)
  * [-v|--verbose]                          # Execute verbose. (default.)
  * [-d|--targets] target-derectory         # Specified target git-repositories
  * [-F|--freeze] repository-path           # Generate .git-parallel.freeze file.

ex)

    git parallel --color auto --jobs 2 --silent -- pull --rebase

    git parallel --maxdepth 3 --jobs 4 -- ::: ls -lha
HELP
}

git::parallel::reccursive_ps_killer() {
    local target_ps=$1
    for x in $(ps --ppid ${target_ps} --no-heading | awk '{ print $1 }'); do
        git::parallel::reccursive_ps_killer "${x}"
    done
    kill -9 ${target_ps}
}

git::parallel::find_targets() {

    MAXDEPTH_OPT=""
    if [[ -n ${GIT_PARALLEL_DEAULT_MAXDEPTH} ]];then
        MAXDEPTH_OPT="-maxdepth "${GIT_PARALLEL_DEAULT_MAXDEPTH}""
    fi

    TARGET_REPOSITORIES=($(find -L "${GIT_PARALLEL_DEAULT_START_DIR}" \
            ${MAXDEPTH_OPT} -name '.git' -type d | \
            perl -p -e "s{^\./}{}" | \
            perl -p -e "s{/\.git$}{}" | \
            grep -v "^$"))
}

git::parallel::command() {
    if [[ ${GIT_PARALLEL_EXEC_CMD} =~ ^[[:blank:]]*:::[[:blank:]]+(.*)$ ]];then
        CMD_MODE="bare"
        CMD=${BASH_REMATCH[1]}
    elif [[ ${GIT_PARALLEL_EXEC_CMD} =~ ^[[:blank:]]*git[[:blank:]]+(.*)$ ]];then
        CMD_MODE="git"
        CMD=${BASH_REMATCH[1]}
    else
        CMD_MODE="git"
        CMD=${GIT_PARALLEL_EXEC_CMD}
    fi
}

git::parallel::color() {
    local color="${GIT_PARALLEL_DEAULT_COLOR_MODE}"

    if [[ $color = always ]];then
        GIT_PARALLEL_COLOR="TRUE"
    elif [[ $color = never ]]; then
        GIT_PARALLEL_COLOR="FALSE"
    elif [[ $color = auto ]]; then
      if [[ -t 1 ]]; then
        GIT_PARALLEL_COLOR="TRUE"
      else
        GIT_PARALLEL_COLOR="FALSE"
      fi
    fi
}

git::parallel::version() {
    echo "git-parallel v1.0.0"
}

git::parallel::freeze() {
    local repo="$1"
    if [ -d ${repo}/.git ];then
        touch ${repo}/.git-parallel.freeze
        echo ${repo} now frozen.
    else
        echo ${repo} is not git-repository. > 2
    fi
}


git::parallel::exit() {
    git::parallel::reccursive_ps_killer $$
}

git::parallel::show_list() {
    git::parallel::find_targets
    for x in ${TARGET_REPOSITORIES[@]};do
        echo "${x}"
    done
}

git::parallel::execute() {
    local repository=$1
    local repository_name=$(basename ${repository})
    local git_command="${GIT_PARALLEL_EXEC_CMD}"

    [ -d "${repository}/.git" ] || return;

    if [[ GIT_PARALLEL_COLOR = TRUE ]];then
        git_color_config="-c color.ui=always"
    elif [[ GIT_PARALLEL_COLOR = FALSE ]];then
        git_color_config="-c color.ui=none"
    fi

    if [ "${GIT_PARALLEL_COLOR}" = TRUE ];then
        print_cmd="\033[30;42mresult\033[0m \033[1;35m${GIT_PARALLEL_EXEC_CMD}\033[0m"
        print_repo_name="\033[1;33m${repository_name}\033[0m"
    else
        print_cmd="result ${GIT_PARALLEL_EXEC_CMD}"
        print_repo_name="${repository_name}"
    fi

    cd ${repository}
    echo -e "${print_cmd} ::: ${print_repo_name}"

    if [ -f "${repository}/.git-parallel.freeze" ];then
        echo skip.
        echo .git-parallel.freeze found.
        echo ${repository} is frozen.
        return
    fi

    if [[ $CMD_MODE = git ]];then
        git -C ${repository} ${git_color_config} ${CMD} 2>&1
    elif [[ $CMD_MODE = bare ]];then
        ${CMD} 2>&1
    fi
    echo
}

git::parallel::job_pack() {
    local repo=${TARGET_REPOSITORIES[0]}
    TARGET_REPOSITORIES=("${TARGET_REPOSITORIES[@]:1}")
    if [[ -d ${repo} ]];then
        exec {task_fd}< <(git::parallel::execute "${repo}")
        FD_LIST=(${FD_LIST[@]} ${task_fd})
    fi
}

git::parallel::main() {
    FD_LIST=()

    git::parallel::command
    git::parallel::color
    git::parallel::find_targets

    if [[ ${GIT_PARALLEL_DEAULT_SILENT_MODE} = FALSE ]];then
        echo "start parallel: ${GIT_PARALLEL_EXEC_CMD} ";
        echo;
    fi

    while true; do
        for x in $(seq "${GIT_PARALLEL_DEAULT_JOBS}"); do
            git::parallel::job_pack
        done
        wait

        if [[ ${GIT_PARALLEL_DEAULT_SILENT_MODE} = TRUE ]];then
            for x in ${FD_LIST[@]}; do
                : <&${x}
            done
        else
            for x in ${FD_LIST[@]}; do
                cat <&${x}
            done
        fi

        if [[ -z ${TARGET_REPOSITORIES} ]];then
            break
        fi
    done
}

if [[ -z $@ ]];then
    git::parallel::help && exit 1
fi

if [[ ! $1 =~ ^-+.*$ ]] || [[ $@ =~ ^-[[:blank:]]+.*$ ]];then
    echo "Unknown option $@" >&2
    exit 1
fi

optspec=":j:m:c:d:-:hvFVlsq"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                help)
                    git::parallel::help && exit 1
                    ;;
                version)
                    git::parallel::version && exit 1
                    ;;
                list)
                    git::parallel::show_list && exit 1
                    ;;
                freeze)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    git::parallel::freeze "${val}" && exit 1
                    ;;
                jobs)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    if [[ ${val} =~ ^[[:digit:]]+$ ]]; then
                        GIT_PARALLEL_DEAULT_JOBS="${val}"
                    else
                        echo "Unknown option --jobs ${val}" >&2
                        exit 1
                    fi
                    ;;
                color)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    if [[ ${val} =~ ^(auto|always|never)$ ]]; then
                        GIT_PARALLEL_DEAULT_COLOR_MODE="${val}"
                    else
                        echo "Unknown option --color ${val}" >&2
                        exit 1
                    fi
                    ;;
                maxdepth)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    if [[ ${val} =~ ^[[:digit:]]+$ ]]; then
                        GIT_PARALLEL_DEAULT_MAXDEPTH="${val}"
                    else
                        echo "Unknown option --maxdepth ${val}" >&2
                        exit 1
                    fi
                    ;;
                target)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    GIT_PARALLEL_DEAULT_START_DIR="${val}"
                    ;;
                silent)
                    GIT_PARALLEL_DEAULT_SILENT_MODE="TRUE"
                    ;;
                verbose)
                    GIT_PARALLEL_DEAULT_SILENT_MODE="FALSE"
                    ;;
                *)
                    echo "Unknown option --${OPTARG}" >&2
                    exit 1
                    ;;
            esac;;
        h)
            git::parallel::help && exit 1
            ;;
        V)
            git::parallel::version && exit 1
            ;;
        l)
            git::parallel::show_list && exit 1
            ;;
        F)
            git::parallel::freeze "${OPTARG}" && exit 1
            ;;
        j)
            if [[ ${OPTARG} =~ ^[[:digit:]]+$ ]]; then
                GIT_PARALLEL_DEAULT_JOBS="${OPTARG}"
            else
                echo "Unknown option -j ${OPTARG}" >&2
                exit 1
            fi
            ;;
        c)
            if [[ ${OPTARG} =~ ^(auto|always|never)$ ]]; then
                GIT_PARALLEL_DEAULT_COLOR_MODE="${OPTARG}"
            else
                echo "Unknown option -c ${OPTARG}" >&2
                exit 1
            fi
            ;;
        m)
            if [[ ${OPTARG} =~ ^[[:digit:]]+$ ]]; then
                GIT_PARALLEL_DEAULT_MAXDEPTH="${OPTARG}"
            else
                echo "Unknown option -m ${OPTARG}" >&2
                exit 1
            fi
            ;;
        d)
            GIT_PARALLEL_DEAULT_START_DIR="${OPTARG}"
            ;;
        q)
            GIT_PARALLEL_DEAULT_SILENT_MODE="TRUE"
            ;;
        v)
            GIT_PARALLEL_DEAULT_SILENT_MODE="FALSE"
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

GIT_PARALLEL_EXEC_CMD=$@

if [[ -z ${GIT_PARALLEL_EXEC_CMD} ]];then
    git::parallel::help && exit 1
fi

git::parallel::main && exit 0

